variable "ami" {}
variable "key_name" {}
variable "public_key_path" {}
variable "web_instance_type" {}
variable "web_security_group" {}
variable "db_instance_type" {}
variable "db_security_group" {}
variable "web_subnet_a" {}
variable "web_subnet_b" {}
variable "db_subnet" {}
variable "aws_profile" {}
